name: Build TWGSL
on: workflow_dispatch
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
      - name: Update submodule
        run: |
             git submodule update --init --recursive
             git submodule update --remote --merge
      - name: Clone/install emsdk
        run: |
             cd ..
             git clone https://github.com/emscripten-core/emsdk.git
             cd emsdk
             ./emsdk install latest
      - name: Clone DepotTools
        run: |
             cd ..
             git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        run: |
             cd ../emsdk
             ./emsdk activate latest
             source "emsdk_env.sh"
             cd ../depot_tools
             export PATH=$(pwd):$PATH
             cd ..
             pwd
             cd twgsl/Dependencies/Tint
             cp standalone.gclient .gclient
             gclient sync
             cd ../../..
             mkdir twgsl_build
             cd twgsl_build
             emcmake cmake ../twgsl
             emmake make twgsl
             ls -a Core/twgsl
      - name: Create artifact directory
        run: |
             mkdir artifact
             cp twgsl_build/Core/twgsl/twgsl.js artifact
             cp twgsl_build/Core/twgsl/twgsl.wasm artifact
      - name: Upload TWGSL artifact Folder
        uses: actions/upload-artifact@v2
        with:
          name: 'TWGSL'
          path: artifact
